export const AuthErrorCodes = {
  REGISTRATION_NOT_ALLOWED: 'REGISTRATION_NOT_ALLOWED',
  INVITATION_REQUIRED: 'INVITATION_REQUIRED',
  INVITATION_INVALID: 'INVITATION_INVALID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type AuthErrorCode = (typeof AuthErrorCodes)[keyof typeof AuthErrorCodes];
