export const JoinErrorCodes = {
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  DOMAIN_NOT_ALLOWED: 'DOMAIN_NOT_ALLOWED',
  NO_ALLOWED_DOMAINS: 'NO_ALLOWED_DOMAINS',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type JoinErrorCode = (typeof JoinErrorCodes)[keyof typeof JoinErrorCodes];
