export const JoinErrorCodes = {
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  DOMAIN_NOT_ALLOWED: 'DOMAIN_NOT_ALLOWED',
  NO_ALLOWED_DOMAINS: 'NO_ALLOWED_DOMAINS',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  INVITATION_EMAIL_MISMATCH: 'INVITATION_EMAIL_MISMATCH',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_NOT_PENDING: 'JOIN_REQUEST_NOT_PENDING',
  JOIN_REQUEST_ALREADY_PENDING: 'JOIN_REQUEST_ALREADY_PENDING',
  JOIN_REQUEST_NOT_APPROVED: 'JOIN_REQUEST_NOT_APPROVED',
  INVITATION_REQUIRED: 'INVITATION_REQUIRED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type JoinErrorCode = (typeof JoinErrorCodes)[keyof typeof JoinErrorCodes];
