export const TimeTrackingErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NO_ACTIVE_ORGANIZATION: 'NO_ACTIVE_ORGANIZATION',
  USER_ALREADY_CLOCKED_IN: 'USER_ALREADY_CLOCKED_IN',
  NO_ACTIVE_SESSION_FOUND: 'NO_ACTIVE_SESSION_FOUND',
  BREAK_ALREADY_ACTIVE: 'BREAK_ALREADY_ACTIVE',
  NO_ACTIVE_BREAK_FOUND: 'NO_ACTIVE_BREAK_FOUND',
  TIMELOG_NOT_FOUND: 'TIMELOG_NOT_FOUND',
  USER_NOT_IN_COMPANY: 'USER_NOT_IN_COMPANY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ACTIVITY_STATUS_NOT_FOUND: 'ACTIVITY_STATUS_NOT_FOUND',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type TimeTrackingErrorCode =
  (typeof TimeTrackingErrorCodes)[keyof typeof TimeTrackingErrorCodes];

export function fail(
  code: TimeTrackingErrorCode,
  message: string
): { success: false; error: { code: string; message: string } } {
  return { success: false, error: { code, message } };
}
